#sources = "3DArtist 21nds aeonsparx ailime al18267 animation91 AnkhM Arev B-BAV badjano BBB blackbelt352 blender4ever blenderesa bonnet Borys96 boustalahit calimanoliveira carre44 cendurar chesshirr ChriGall clione ComiG DaCool dak34384 DanielCrane Darkane001 DeadScrypt delanop divingpixel edmondwu1022 einball EmpireProperties Empizz Erathien estajxo Fadge FidoDidoVN Fpsiegel FuzzyWuzzie gerotex Ghreen gronlokke Gruemilk GustavByC hand_solo Harry_Hegel Hellboj herrie highbeamstudios highsinnc HMU holoJero howkj1 IAMTHETHORN iccha IcedClementi imreviljoen inbetween IncredibleSheep indiemax isaacsmith iwoj jccbasel jeanrosa jimmywong jimoniak jk1swt jonatanhedborg JonathanTab Justoch kanomon KevGamesUltimate kira96c kissgyula kusius lachoneus Liberty009 Lithen lorislibero LunarPenguin manujarvinen MarcHumphreys marco1960 martyfinkle MasterBen MatteCrystalV2 Matthijz98 Maximon mblackburn MC0 Metallord misscore montykutyi MrBlack1772 mrgoog N3BB3Z4R najeb Nibbler19 nigelat nightshaade ObelX paulchop Per22 Perfect_Pint Phenax Phyveon pilly33 pitvandyck pixby Poesie_Render qcgeneral29 Raimund58 RandomRenderings romasso RPBCACUEAIIBH sakuukuli Saxeen Scbenoit scribblemaniac Sealund sjijoseph somasimple stefanV stom stuartc Swag tate TomPoulot tomwe1 tonyf69 turtleRender TylerPin unreal UnRealCloud uwepost vitorboschi voidNK Volkereigen werauchimmer WestPotomacTSA Whippie winapple wuls zerdnog Zersal"
#sources = "-Samino- albaner alexbo AnkhM ANTIS111 apple1728 Arev Arthur_Weiss AshiroConanVS AwVwARage blender4ever blenderesa BroBpony CG-Kuba chesshirr ChriGall cloudyruin ComiG crotte-bidou curiosity91 danp Darknoodles dfield divingpixel drawdecs Edward el71Gato EmpireProperties Empizz EricFelbs FelipeSevero fhecrewdavid flyke formation frosta95 fstadin greatwhite grooveboy Gruemilk GustavByC hand_solo Harry_Hegel heinzelnisse highbeamstudios IcedClementi inakiblender Jagdoe jbene jimoniak JMcAllister jonatanhedborg kaptaink_cg KevGamesUltimate kingvlad kira96c kornpcgamer kostirez1 kurlak lachoneus Leumeister Liberty009 littleright LucasPMagno lukaa Mad_Axell Mario_Verkerk markos MC0 MMaire MrBlack1772 mrgoog mydigitalwalk myperduk MZiemys Nibbler19 ObelX Paraklletoss paulchop Phyveon pitvandyck Poesie_Render polyboy_3D qcgeneral29 Raimund58 RandomRenderings rochbenritter RollCONTAiNER RPBCACUEAIIBH Rubyjunk Rwthegamer sakuukuli scribblemaniac ShadowSheep shallrender sillywilly sirflankalot somasimple stom Swag tate thunder_cg Tiinea TomPoulot tomwe1 turtleRender ulissesn warnotte weredwarf wesseb winapple xddsniper xyz zerdnog"
sources = "3DArtist Allshevski Andrin61 APSRenderingandAnimation Arev Argumentator attila16 beefbayonet Belmont BIgGoga blender4ever blenderesa BlenderRookie Bringidon CactusCubesMatt CaptainSweet Cdanimation danp DensePixel divingpixel edmondwu1022 EricFelbs formation gerotex goldengel Gruemilk hand_solo hetsumani holoJero howkj1 Idk_yara isaacsmith jimmywong jimoniak jk1swt JonathanTab kikr4140 kira96c kissgyula kouta602 koves lachoneus LK84 LucasPMagno lxne MC0 MrBlack1772 mrgoog Mr_Lamppost nezumi Nibbler19 ObelX obliviousfre olivion Pastel paulchop peppenova Perfect_Pint peter_kolm pilly33 qcgeneral29 Raimund58 RenderFun ridunc Runouw Rwthegamer savvov Saxeen Simmer65 SneakyMrRed somasimple Struffel TomPoulot tomwe1 tongjie VA-Vision valsevent voidNK Volodey vrumfondel wesseb zbx"
output = ""

for source in sources.split(' '):
	output += ', "' + source  + '"'

print output
